/* Document wording PT/EN/FR. Reviewed text: change only with Andrew's approval (see CLAUDE.md). */
export const DOCT={
pt:{
loc:'pt-BR',sub:'Assistência Técnica Especializada',wapp:'WhatsApp',num:'Nº',
k_name:'Nome / instituição',k_ac:'A/C',k_doc:'CPF / CNPJ',k_addr:'Endereço',k_city:'Cidade',k_phone:'Telefone',k_email:'E-mail',
k_equip:'Equipamento',k_brand:'Marca',k_model:'Modelo',k_serial:'Nº de série',k_volt:'Tensão',
sec_client:'Cliente',sec_equip:'Equipamento',obs:'Observações',
place:'{city}, {date}.',
sig_tech:'Técnico responsável, 4V Manutencoes',sig_client:'Cliente — nome, cargo e carimbo',sig_date:'Data: ___/___/______',
months:{3:'3 (três) meses',6:'6 (seis) meses',12:'12 (doze) meses'},
fn:{G:'Termo-de-Garantia',E:'Termo-de-Entrega',C:'Contrato-de-Venda',R:'Recibo'},
G_title:'TERMO DE GARANTIA DE SERVIÇO',sec_service:'Serviço executado',k_svcdate:'Data do serviço',k_desc:'Descrição do serviço',th_qty:'Qtd.',th_part:'Peça substituída',sec_warranty:'Garantia',
g1:'A **4V Manutencoes** garante o serviço descrito acima pelo prazo de **{term}**, contado a partir de **{start}**.',
g2:'Esta garantia cobre a mão de obra do serviço executado e as peças substituídas listadas acima. Ela é complementar à garantia legal prevista no Código de Defesa do Consumidor (arts. 26 e 50).',
g3:'O atendimento em garantia não tem custo para o cliente.',
g4:'Para acionar a garantia, entre em contato pelo WhatsApp **{tel}** ou pelo e-mail **{email}** e informe o número deste termo.',
nocover:'A garantia não cobre:',
nc:['Uso em desacordo com o manual do fabricante.','Ligação em tensão elétrica errada, quedas, batidas, descargas elétricas ou variações da rede.','Abertura ou conserto por terceiros, ou selo de garantia rompido.','Peças e componentes que não foram trocados neste serviço.','Desgaste natural de itens de consumo e falta da limpeza ou manutenção indicadas.'],
E_title:'TERMO DE ENTREGA TÉCNICA E ORIENTAÇÕES DE USO',
E_intro:'Entregamos o equipamento abaixo revisado e em funcionamento, com as seguintes orientações de uso:',
E_orient:'Orientações de uso',
E_warr:'Este equipamento tem garantia de **{term}** a partir de **{start}**. O atendimento em garantia não tem custo para o cliente.',
E_decl:'Declaro que recebi o equipamento em funcionamento e as orientações acima.',
E_by:'Entregue por: {name}, 4V Manutencoes',E_recv:'Recebido por — nome, cargo e carimbo',
o_selo:'Confira o selo de garantia no ato da entrega. Selo rompido cancela a garantia.',
o_contato:'Em caso de dúvida ou falha durante o uso, interrompa o funcionamento e entre em contato com o suporte técnico: WhatsApp {tel}.',
presets:{
autoclave:['Acompanhe o equipamento durante o ciclo: o aviso sonoro de mudança de fase e de fim de ciclo é baixo.','Coloque somente a quantidade de material indicada no manual do fabricante. Deixe espaço para a circulação do vapor e não obstrua a saída de vapor.','Respeite o intervalo entre um ciclo e outro indicado no manual.','Use somente água destilada no reservatório.','Limpe a câmara interna uma vez por semana.','Verifique sempre se a mangueira de saída de vapor não está obstruída.'],
odonto:['Ligue o equipamento somente na tensão elétrica indicada na etiqueta.','Ao fim de cada atendimento, aspire água limpa pelo sugador e limpe a cuspideira.','Lubrifique as canetas (alta rotação e micromotor) conforme a orientação do fabricante.','Drene diariamente a água acumulada no compressor de ar.','Desligue a chave geral ao fim do expediente.','Não use produtos abrasivos ou solventes no estofamento e nas partes plásticas.'],
estufa:['Ligue o equipamento somente na tensão elétrica indicada na etiqueta.','Não ultrapasse a temperatura máxima indicada pelo fabricante.','Não obstrua as aberturas de ventilação e deixe espaço entre o material e as paredes internas.','Aguarde a estufa esfriar antes de abrir para limpeza.','Limpe a câmara interna com pano úmido e sabão neutro; não use produtos abrasivos.'],
exaustao:['Ligue o exaustor antes de começar o trabalho e mantenha-o ligado durante todo o uso.','Trabalhe com a janela (guilhotina) na altura indicada pelo fabricante.','Não guarde produtos ou materiais dentro da cabine.','Não bloqueie as aberturas de exaustão.','Limpe a superfície de trabalho após o uso.'],
bio:['Ligue a cabine antes do uso e aguarde o tempo de estabilização indicado pelo fabricante.','Nunca use a lâmpada UV com o operador presente.','Não bloqueie as grelhas frontal e traseira.','Desinfete a superfície de trabalho antes e depois do uso, conforme o protocolo do laboratório.','Respeite a periodicidade de manutenção preventiva indicada pelo fabricante.'],
outro:['Ligue o equipamento somente na tensão elétrica indicada na etiqueta.','Siga as instruções do manual do fabricante.','Mantenha o equipamento limpo e em local ventilado.']},
C_title:'CONTRATO PARTICULAR DE COMPRA E VENDA DE EQUIPAMENTO',
C_seller:'**{razao}**, inscrita no CNPJ sob o nº {cnpj}, Inscrição Estadual {ie}, com sede em {addr}, {city}, CEP {cep}, neste ato representada por {resp}, doravante denominada simplesmente **VENDEDOR**.',
C_pf:'**{name}**, {nat}, portador(a) do RG nº {rg}, inscrito(a) no CPF sob o nº {doc}, residente em {addr}, {city}, CEP {cep}, doravante denominado(a) simplesmente **COMPRADOR**.',
C_pj:'**{name}**, inscrita no CNPJ sob o nº {doc}, com sede em {addr}, {city}, CEP {cep}, neste ato representada por {rep}, doravante denominada simplesmente **COMPRADOR**.',
C_agree:'As partes acima têm entre si justo e contratado o que segue:',
C_h:['CLÁUSULA 1ª – DO OBJETO','CLÁUSULA 2ª – DO PREÇO E DO PAGAMENTO','CLÁUSULA 3ª – DA ENTREGA E DA POSSE','CLÁUSULA 4ª – DO TRANSPORTE','CLÁUSULA 5ª – DA ORIGEM E DOS ÔNUS','CLÁUSULA 6ª – DA GARANTIA','CLÁUSULA 7ª – DA INSTALAÇÃO E DO USO','CLÁUSULA 8ª – DISPOSIÇÕES GERAIS','CLÁUSULA 9ª – DO FORO'],
C_1:'O VENDEDOR declara ser o legítimo proprietário do(s) equipamento(s) abaixo, que vende ao COMPRADOR no estado **{state}**:',
C_th:['Equipamento','Nº de série'],
states:{usado:'usado e revisado',novo:'novo',recond:'recondicionado'},
C_2:'O preço total, justo e certo, é de **R$ {value} ({words})**, pago da seguinte forma: {pay}{det}.',
pays:{avista:'à vista, na entrega',pix:'por PIX',parc:'parcelado'},
C_3:'O COMPRADOR toma posse do equipamento em **{date}**, data a partir da qual passa a responder por sua guarda e conservação.',
C_4:{retira:'O equipamento será retirado pelo COMPRADOR, sem custo para o VENDEDOR.',transp:'O equipamento será despachado por transportadora indicada pelo COMPRADOR, que arcará com o frete e com os riscos do transporte.',vend:'O VENDEDOR entregará o equipamento no endereço do COMPRADOR.'},
C_5:'O VENDEDOR garante que o equipamento está livre e desembaraçado de qualquer ônus, dívida, penhora ou restrição. Caso o equipamento venha a ser retirado do COMPRADOR por motivo anterior a esta venda, o VENDEDOR devolverá o valor recebido, corrigido monetariamente e acrescido dos juros legais.',
C_6:['a) O VENDEDOR concede garantia de **{term}** contra defeitos de funcionamento, contada da data de entrega do equipamento.','b) A garantia perde a validade se o selo de garantia for rompido, se o equipamento sofrer queda, acidente ou dano causado por terceiros, ou se for ligado em tensão elétrica errada.','c) O atendimento em garantia não tem custo para o COMPRADOR, que deve acioná-lo pelo WhatsApp {tel} ou pelo e-mail {email}.'],
C_7:'O COMPRADOR declara ter recebido o equipamento testado e em funcionamento e se compromete a instalá-lo e utilizá-lo conforme o manual do fabricante, na tensão elétrica correta.',
C_8:'Este contrato é celebrado em caráter irrevogável e irretratável e obriga as partes, seus herdeiros e sucessores.',
C_9:'Fica eleito o foro da Comarca de **{foro}** para resolver qualquer questão referente a este contrato, com renúncia a qualquer outro, por mais privilegiado que seja.',
C_close:'E, por estarem de acordo, as partes assinam este contrato em 2 (duas) vias de igual teor e forma, na presença das 2 (duas) testemunhas abaixo.',
C_sellerRole:'VENDEDOR',C_buyerRole:'COMPRADOR',C_wit:'Testemunha {n}',C_name:'Nome: {v}',C_cpf:'CPF: {v}',C_cnpj:'CNPJ {v}',C_cpfdoc:'CPF {v}',C_cpfcnpj:'CPF/CNPJ {v}',
R_title:'RECIBO',
R_1:'Recebi de **{name}**, CPF/CNPJ {doc}, a importância de **R$ {value} ({words})**, referente a {ref}.',
R_2:'Forma de pagamento: {pay}.',
R_3:'Para maior clareza, firmo o presente recibo, dando plena quitação do valor recebido.',
rpays:{dinheiro:'Dinheiro',pix:'PIX',transf:'Transferência bancária',cartao:'Cartão',boleto:'Boleto',cheque:'Cheque'}
},
en:{
loc:'en-US',sub:'Specialized Technical Service',wapp:'WhatsApp',num:'No.',
k_name:'Name / institution',k_ac:'Attn.',k_doc:'CPF / CNPJ',k_addr:'Address',k_city:'City',k_phone:'Phone',k_email:'E-mail',
k_equip:'Equipment',k_brand:'Brand',k_model:'Model',k_serial:'Serial no.',k_volt:'Voltage',
sec_client:'Client',sec_equip:'Equipment',obs:'Notes',
place:'{city}, {date}.',
sig_tech:'Responsible technician, 4V Manutencoes',sig_client:'Client — name, position and stamp',sig_date:'Date: ___/___/______',
months:{3:'3 (three) months',6:'6 (six) months',12:'12 (twelve) months'},
fn:{G:'Warranty-Certificate',E:'Delivery-Note',C:'Sales-Contract',R:'Receipt'},
G_title:'SERVICE WARRANTY CERTIFICATE',sec_service:'Service performed',k_svcdate:'Date of service',k_desc:'Description of the service',th_qty:'Qty.',th_part:'Part replaced',sec_warranty:'Warranty',
g1:'**4V Manutencoes** warrants the service described above for **{term}**, counted from **{start}**.',
g2:'This warranty covers the labor of the service performed and the replaced parts listed above. It is in addition to the statutory warranty provided by the Brazilian Consumer Protection Code (arts. 26 and 50).',
g3:'Warranty service is free of charge to the client.',
g4:'To claim the warranty, contact us on WhatsApp **{tel}** or by e-mail **{email}** and quote the number of this certificate.',
nocover:'The warranty does not cover:',
nc:['Use contrary to the manufacturer’s manual.','Connection to the wrong electrical voltage, drops, impacts, electrical discharges or power-grid fluctuations.','Opening or repair by third parties, or a broken warranty seal.','Parts and components that were not replaced in this service.','Normal wear of consumable items and lack of the cleaning or maintenance indicated.'],
E_title:'DELIVERY NOTE AND USAGE INSTRUCTIONS',
E_intro:'We are handing over the equipment below, serviced and in working order, with the following usage instructions:',
E_orient:'Usage instructions',
E_warr:'This equipment is under warranty for **{term}** from **{start}**. Warranty service is free of charge to the client.',
E_decl:'I declare that I received the equipment in working order and the instructions above.',
E_by:'Delivered by: {name}, 4V Manutencoes',E_recv:'Received by — name, position and stamp',
o_selo:'Check the warranty seal when you receive the equipment. A broken seal voids the warranty.',
o_contato:'If you have any questions or a fault occurs during use, stop the equipment and contact technical support: WhatsApp {tel}.',
presets:{
autoclave:['Stay with the equipment during the cycle: the beep that signals phase changes and the end of the cycle is quiet.','Load only the amount of material indicated in the manufacturer’s manual. Leave room for the steam to circulate and do not block the steam outlet.','Respect the interval between cycles stated in the manual.','Use only distilled water in the reservoir.','Clean the inner chamber once a week.','Always check that the steam outlet hose is not blocked.'],
odonto:['Plug in the equipment only at the voltage shown on the label.','After each patient, suction clean water through the suction tip and clean the cuspidor.','Lubricate the handpieces (high-speed and micromotor) following the manufacturer’s instructions.','Drain the water that builds up in the air compressor every day.','Switch off the main switch at the end of the working day.','Do not use abrasive products or solvents on the upholstery and plastic parts.'],
estufa:['Plug in the equipment only at the voltage shown on the label.','Do not exceed the maximum temperature stated by the manufacturer.','Do not block the ventilation openings, and leave space between the material and the inner walls.','Wait for the oven to cool down before opening it for cleaning.','Clean the inner chamber with a damp cloth and neutral soap; do not use abrasive products.'],
exaustao:['Turn on the exhaust fan before starting work and keep it on throughout use.','Work with the sash (sliding window) at the height indicated by the manufacturer.','Do not store products or materials inside the cabinet.','Do not block the exhaust openings.','Clean the work surface after use.'],
bio:['Turn on the cabinet before use and wait for the stabilization time indicated by the manufacturer.','Never use the UV lamp while the operator is present.','Do not block the front and rear grilles.','Disinfect the work surface before and after use, following the laboratory protocol.','Follow the preventive maintenance schedule indicated by the manufacturer.'],
outro:['Plug in the equipment only at the voltage shown on the label.','Follow the instructions in the manufacturer’s manual.','Keep the equipment clean and in a ventilated place.']},
C_title:'PRIVATE EQUIPMENT PURCHASE AND SALE AGREEMENT',
C_seller:'**{razao}**, registered under CNPJ (Brazilian company tax ID) no. {cnpj}, State Registration {ie}, headquartered at {addr}, {city}, ZIP {cep}, herein represented by {resp}, hereinafter simply referred to as the **SELLER**.',
C_pf:'**{name}**, {nat}, holder of ID card (RG) no. {rg}, registered under CPF (Brazilian individual tax ID) no. {doc}, residing at {addr}, {city}, ZIP {cep}, hereinafter simply referred to as the **BUYER**.',
C_pj:'**{name}**, registered under CNPJ no. {doc}, headquartered at {addr}, {city}, ZIP {cep}, herein represented by {rep}, hereinafter simply referred to as the **BUYER**.',
C_agree:'The parties above have agreed to the following:',
C_h:['CLAUSE 1 – SUBJECT MATTER','CLAUSE 2 – PRICE AND PAYMENT','CLAUSE 3 – DELIVERY AND POSSESSION','CLAUSE 4 – TRANSPORT','CLAUSE 5 – ORIGIN AND ENCUMBRANCES','CLAUSE 6 – WARRANTY','CLAUSE 7 – INSTALLATION AND USE','CLAUSE 8 – GENERAL PROVISIONS','CLAUSE 9 – JURISDICTION'],
C_1:'The SELLER declares to be the lawful owner of the equipment listed below, which is sold to the BUYER in **{state}** condition:',
C_th:['Equipment','Serial no.'],
states:{usado:'used and serviced',novo:'new',recond:'refurbished'},
C_2:'The total, fair and agreed price is **R$ {value} ({words})**, paid as follows: {pay}{det}.',
pays:{avista:'in full, on delivery',pix:'by PIX (instant bank transfer)',parc:'in installments'},
C_3:'The BUYER takes possession of the equipment on **{date}**, from which date the BUYER is responsible for its custody and care.',
C_4:{retira:'The equipment will be collected by the BUYER, at no cost to the SELLER.',transp:'The equipment will be shipped by a carrier chosen by the BUYER, who will bear the freight and the risks of transport.',vend:'The SELLER will deliver the equipment to the BUYER’s address.'},
C_5:'The SELLER warrants that the equipment is free and clear of any lien, debt, seizure or restriction. Should the equipment be taken from the BUYER for a reason prior to this sale, the SELLER will refund the amount received, adjusted for inflation and increased by statutory interest.',
C_6:['a) The SELLER grants a warranty of **{term}** against operating defects, counted from the delivery date of the equipment.','b) The warranty is void if the warranty seal is broken, if the equipment suffers a fall, accident or damage caused by third parties, or if it is connected to the wrong electrical voltage.','c) Warranty service is free of charge to the BUYER, who must request it by WhatsApp {tel} or by e-mail {email}.'],
C_7:'The BUYER declares to have received the equipment tested and in working order and undertakes to install and use it according to the manufacturer’s manual, at the correct electrical voltage.',
C_8:'This agreement is entered into on an irrevocable and irreversible basis and binds the parties, their heirs and successors.',
C_9:'The courts of the District of **{foro}** are chosen to settle any dispute relating to this agreement, waiving any other, however privileged.',
C_close:'In witness whereof, the parties sign this agreement in 2 (two) copies of equal content and form, in the presence of the 2 (two) witnesses below.',
C_sellerRole:'SELLER',C_buyerRole:'BUYER',C_wit:'Witness {n}',C_name:'Name: {v}',C_cpf:'CPF: {v}',C_cnpj:'CNPJ {v}',C_cpfdoc:'CPF {v}',C_cpfcnpj:'CPF/CNPJ {v}',
R_title:'RECEIPT',
R_1:'Received from **{name}**, CPF/CNPJ {doc}, the amount of **R$ {value} ({words})**, in payment for {ref}.',
R_2:'Payment method: {pay}.',
R_3:'For the avoidance of doubt, I sign this receipt, giving full discharge for the amount received.',
rpays:{dinheiro:'Cash',pix:'PIX',transf:'Bank transfer',cartao:'Card',boleto:'Boleto',cheque:'Check'}
},
fr:{
loc:'fr-FR',sub:'Assistance technique spécialisée',wapp:'WhatsApp',num:'N°',
k_name:'Nom / établissement',k_ac:'À l’att. de',k_doc:'CPF / CNPJ',k_addr:'Adresse',k_city:'Ville',k_phone:'Téléphone',k_email:'E-mail',
k_equip:'Équipement',k_brand:'Marque',k_model:'Modèle',k_serial:'N° de série',k_volt:'Tension',
sec_client:'Client',sec_equip:'Équipement',obs:'Remarques',
place:'{city}, le {date}.',
sig_tech:'Technicien responsable, 4V Manutencoes',sig_client:'Client — nom, fonction et cachet',sig_date:'Date : ___/___/______',
months:{3:'3 (trois) mois',6:'6 (six) mois',12:'12 (douze) mois'},
fn:{G:'Certificat-de-Garantie',E:'Bon-de-Livraison',C:'Contrat-de-Vente',R:'Recu'},
G_title:'CERTIFICAT DE GARANTIE DE SERVICE',sec_service:'Intervention réalisée',k_svcdate:'Date de l’intervention',k_desc:'Description de l’intervention',th_qty:'Qté',th_part:'Pièce remplacée',sec_warranty:'Garantie',
g1:'**4V Manutencoes** garantit l’intervention décrite ci-dessus pour une durée de **{term}**, à compter du **{start}**.',
g2:'Cette garantie couvre la main-d’œuvre de l’intervention réalisée et les pièces remplacées listées ci-dessus. Elle s’ajoute à la garantie légale prévue par le Code brésilien de défense du consommateur (art. 26 et 50).',
g3:'Le service sous garantie est gratuit pour le client.',
g4:'Pour faire jouer la garantie, contactez-nous par WhatsApp au **{tel}** ou par e-mail à **{email}** en indiquant le numéro de ce certificat.',
nocover:'La garantie ne couvre pas :',
nc:['Une utilisation non conforme au manuel du fabricant.','Un branchement à une mauvaise tension électrique, des chutes, des chocs, des décharges électriques ou des variations du réseau.','Une ouverture ou une réparation par des tiers, ou un sceau de garantie rompu.','Les pièces et composants qui n’ont pas été remplacés lors de cette intervention.','L’usure normale des consommables et le défaut de nettoyage ou d’entretien indiqués.'],
E_title:'BON DE LIVRAISON ET CONSIGNES D’UTILISATION',
E_intro:'Nous remettons l’équipement ci-dessous, révisé et en état de fonctionnement, avec les consignes d’utilisation suivantes :',
E_orient:'Consignes d’utilisation',
E_warr:'Cet équipement est garanti pour une durée de **{term}** à compter du **{start}**. Le service sous garantie est gratuit pour le client.',
E_decl:'Je déclare avoir reçu l’équipement en état de fonctionnement et les consignes ci-dessus.',
E_by:'Remis par : {name}, 4V Manutencoes',E_recv:'Reçu par — nom, fonction et cachet',
o_selo:'Vérifiez le sceau de garantie à la réception de l’équipement. Un sceau rompu annule la garantie.',
o_contato:'En cas de doute ou de panne pendant l’utilisation, arrêtez l’équipement et contactez le support technique : WhatsApp {tel}.',
presets:{
autoclave:['Restez près de l’équipement pendant le cycle : le signal sonore indiquant les changements de phase et la fin du cycle est faible.','Ne chargez que la quantité de matériel indiquée dans le manuel du fabricant. Laissez de la place pour la circulation de la vapeur et ne bouchez pas la sortie de vapeur.','Respectez l’intervalle entre deux cycles indiqué dans le manuel.','Utilisez uniquement de l’eau distillée dans le réservoir.','Nettoyez la chambre intérieure une fois par semaine.','Vérifiez toujours que le tuyau de sortie de vapeur n’est pas obstrué.'],
odonto:['Branchez l’équipement uniquement à la tension indiquée sur l’étiquette.','Après chaque patient, aspirez de l’eau propre avec l’aspirateur chirurgical et nettoyez le crachoir.','Lubrifiez les pièces à main (haute vitesse et micromoteur) selon les instructions du fabricant.','Purgez chaque jour l’eau accumulée dans le compresseur d’air.','Coupez l’interrupteur général à la fin de la journée de travail.','N’utilisez ni produits abrasifs ni solvants sur le revêtement et les parties en plastique.'],
estufa:['Branchez l’équipement uniquement à la tension indiquée sur l’étiquette.','Ne dépassez pas la température maximale indiquée par le fabricant.','N’obstruez pas les ouvertures de ventilation et laissez un espace entre le matériel et les parois intérieures.','Attendez que l’étuve refroidisse avant de l’ouvrir pour la nettoyer.','Nettoyez la chambre intérieure avec un chiffon humide et du savon neutre ; n’utilisez pas de produits abrasifs.'],
exaustao:['Allumez l’extracteur avant de commencer le travail et laissez-le en marche pendant toute l’utilisation.','Travaillez avec la vitre guillotine à la hauteur indiquée par le fabricant.','Ne rangez ni produits ni matériel à l’intérieur de la sorbonne.','Ne bouchez pas les ouvertures d’extraction.','Nettoyez le plan de travail après l’utilisation.'],
bio:['Allumez le poste avant l’utilisation et attendez le temps de stabilisation indiqué par le fabricant.','N’utilisez jamais la lampe UV en présence de l’opérateur.','Ne bouchez pas les grilles avant et arrière.','Désinfectez le plan de travail avant et après l’utilisation, selon le protocole du laboratoire.','Respectez la périodicité de maintenance préventive indiquée par le fabricant.'],
outro:['Branchez l’équipement uniquement à la tension indiquée sur l’étiquette.','Suivez les instructions du manuel du fabricant.','Gardez l’équipement propre et dans un endroit aéré.']},
C_title:'CONTRAT PRIVÉ DE VENTE D’ÉQUIPEMENT',
C_seller:'**{razao}**, inscrite au CNPJ (registre fiscal brésilien des entreprises) sous le n° {cnpj}, Inscription d’État {ie}, dont le siège est situé {addr}, {city}, CEP {cep}, ici représentée par {resp}, ci-après dénommée simplement le **VENDEUR**.',
C_pf:'**{name}**, de nationalité {nat}, titulaire de la pièce d’identité (RG) n° {rg}, inscrit(e) au CPF (numéro fiscal brésilien des particuliers) sous le n° {doc}, domicilié(e) {addr}, {city}, CEP {cep}, ci-après dénommé(e) simplement l’**ACHETEUR**.',
C_pj:'**{name}**, inscrite au CNPJ sous le n° {doc}, dont le siège est situé {addr}, {city}, CEP {cep}, ici représentée par {rep}, ci-après dénommée simplement l’**ACHETEUR**.',
C_agree:'Les parties ci-dessus ont convenu de ce qui suit :',
C_h:['CLAUSE 1 – OBJET','CLAUSE 2 – PRIX ET PAIEMENT','CLAUSE 3 – LIVRAISON ET PRISE DE POSSESSION','CLAUSE 4 – TRANSPORT','CLAUSE 5 – ORIGINE ET CHARGES','CLAUSE 6 – GARANTIE','CLAUSE 7 – INSTALLATION ET UTILISATION','CLAUSE 8 – DISPOSITIONS GÉNÉRALES','CLAUSE 9 – JURIDICTION COMPÉTENTE'],
C_1:'Le VENDEUR déclare être le propriétaire légitime de l’équipement (ou des équipements) ci-dessous, qu’il vend à l’ACHETEUR dans l’état suivant : **{state}**.',
C_th:['Équipement','N° de série'],
states:{usado:'d’occasion et révisé',novo:'neuf',recond:'reconditionné'},
C_2:'Le prix total, juste et convenu, est de **R$ {value} ({words})**, payé comme suit : {pay}{det}.',
pays:{avista:'au comptant, à la livraison',pix:'par PIX (virement bancaire instantané)',parc:'en plusieurs versements'},
C_3:'L’ACHETEUR prend possession de l’équipement le **{date}**, date à partir de laquelle il en assume la garde et la conservation.',
C_4:{retira:'L’équipement sera retiré par l’ACHETEUR, sans frais pour le VENDEUR.',transp:'L’équipement sera expédié par un transporteur désigné par l’ACHETEUR, qui supportera le fret et les risques du transport.',vend:'Le VENDEUR livrera l’équipement à l’adresse de l’ACHETEUR.'},
C_5:'Le VENDEUR garantit que l’équipement est libre de toute charge, dette, saisie ou restriction. Si l’équipement venait à être retiré à l’ACHETEUR pour un motif antérieur à la présente vente, le VENDEUR rembourserait la somme reçue, corrigée monétairement et majorée des intérêts légaux.',
C_6:['a) Le VENDEUR accorde une garantie de **{term}** contre les défauts de fonctionnement, à compter de la date de livraison de l’équipement.','b) La garantie devient caduque si le sceau de garantie est rompu, si l’équipement subit une chute, un accident ou un dommage causé par des tiers, ou s’il est branché à une mauvaise tension électrique.','c) Le service sous garantie est gratuit pour l’ACHETEUR, qui doit le demander par WhatsApp au {tel} ou par e-mail à {email}.'],
C_7:'L’ACHETEUR déclare avoir reçu l’équipement testé et en état de fonctionnement et s’engage à l’installer et à l’utiliser conformément au manuel du fabricant, à la tension électrique correcte.',
C_8:'Le présent contrat est conclu à titre irrévocable et irrétractable et lie les parties, leurs héritiers et leurs ayants cause.',
C_9:'Le tribunal de la juridiction de **{foro}** est choisi pour régler tout litige relatif au présent contrat, à l’exclusion de tout autre, même plus privilégié.',
C_close:'En foi de quoi, les parties signent le présent contrat en 2 (deux) exemplaires de même teneur et de même forme, en présence des 2 (deux) témoins ci-dessous.',
C_sellerRole:'VENDEUR',C_buyerRole:'ACHETEUR',C_wit:'Témoin {n}',C_name:'Nom : {v}',C_cpf:'CPF : {v}',C_cnpj:'CNPJ {v}',C_cpfdoc:'CPF {v}',C_cpfcnpj:'CPF/CNPJ {v}',
R_title:'REÇU',
R_1:'J’ai reçu de **{name}**, CPF/CNPJ {doc}, la somme de **R$ {value} ({words})**, au titre de {ref}.',
R_2:'Mode de paiement : {pay}.',
R_3:'Pour valoir ce que de droit, je signe le présent reçu, donnant pleine quittance de la somme reçue.',
rpays:{dinheiro:'Espèces',pix:'PIX',transf:'Virement bancaire',cartao:'Carte',boleto:'Boleto',cheque:'Chèque'}
}};
