import type { Content, Faq } from './types';

const FAQ_WARRANTY: Faq = { q: 'How long is the service warranty?', a: 'Every service has a minimum 3-month warranty, stated in writing in the warranty certificate. Depending on the service, the term can be longer.' };
const FAQ_FREE: Faq = { q: 'Is warranty service charged?', a: 'No. Warranty service is free of charge for the client.' };
const FAQ_PREVENTIVE: Faq = { q: 'Do you do preventive maintenance?', a: 'Yes. Preventive maintenance checks the equipment before it breaks down, which lowers the risk of interrupting your work and extends its service life.' };
const FAQ_PUBLIC: Faq = { q: 'Do you work with universities and public bodies?', a: 'Yes. 4V Manutencoes has served USP, UNESP, Unifesp and city halls in the region.' };
const FAQ_QUOTE: Faq = { q: 'How do I ask for a quote?', a: 'Message us on WhatsApp at {phone}, e-mail {email} or use the contact form. Tell us the equipment, brand and model and describe the problem. If you can, send a photo of the equipment label.' };
const FAQ_DOCS: Faq = { q: 'Do I get a document for the service?', a: 'Yes. You receive the warranty certificate and the equipment usage instructions in writing.' };

export const en: Content = {
  ui: {
    htmlLang: 'en', ogLocale: 'en_US', langName: 'English',
    skip: 'Skip to content', menu: 'Menu', home: 'Home',
    waBtn: 'Message on WhatsApp', mailBtn: 'Send an e-mail', callBtn: 'Call',
    phoneLabel: 'WhatsApp and phone', emailLabel: 'E-mail', addressLabel: 'Address', cnpjLabel: 'CNPJ (company ID)',
    servicesTitle: 'Services', problemsTitle: 'Common problems we fix', faqTitle: 'Frequently asked questions',
    relatedTitle: 'Other services', seeExperience: 'See the experience of 4V Manutencoes',
    warrantyTitle: 'Written warranty',
    warrantySeal: ['MINIMUM WARRANTY', '3', 'MONTHS', 'ON EVERY SERVICE'],
    warrantyPoints: [
      'Minimum 3-month warranty on every service. Depending on the service, the term can be longer.',
      'Warranty service is free of charge for the client.',
      'You receive the warranty certificate and the equipment usage instructions in writing.',
    ],
    contactTitle: 'Ask for a quote',
    contactLead: 'Talk directly to Valdir. Tell him the equipment, brand, model and the problem.',
    howTitle: 'How it works',
    howSteps: [
      'Message on WhatsApp or send an e-mail describing the equipment and the problem.',
      'The equipment is assessed.',
      'The service is done and tested.',
      'You get the equipment back with a warranty certificate and usage instructions.',
    ],
    areasLine: 'Service in Jacareí, São José dos Campos, the Paraíba Valley and the North Coast of São Paulo state, Brazil.',
    langSwitch: 'Language',
    footerServices: 'Services', footerAbout: 'The company',
    form: {
      title: 'Quote request form',
      lead: 'Fill in what you know. Valdir will reply by e-mail or WhatsApp.',
      name: 'Name', org: 'Company or institution', city: 'City', phone: 'Phone or WhatsApp', email: 'E-mail',
      equipment: 'Equipment (brand and model)', equipmentHint: 'E.g. Cristófoli 21-litre autoclave', message: 'Message',
      send: 'Send message', required: 'required',
      tooFast: 'Please check your details and tap “Send message” again.',
      subject: 'Quote request from the website (EN)',
    },
    portraitAlt: 'Valdir de Paula Bicudo, technician at 4V Manutencoes',
    logoAlt: '4V Manutencoes',
    vcard: 'Save the contact to your phone (vCard)',
    photoCaptionTitle: 'Valdir Bicudo',
    photoCaption: 'Talk directly to Valdir on WhatsApp.',
  },

  home: {
    slug: '',
    title: 'Medical and Laboratory Equipment Maintenance | 4V',
    description: 'Corrective and preventive maintenance of autoclaves, lab ovens, fume hoods and dental equipment in Jacareí, Brazil. Written warranty.',
    h1: 'Maintenance of medical, laboratory and dental equipment',
    nav: 'Home',
    eyebrow: 'Specialised Technical Service',
    lead: 'Corrective and preventive maintenance with a written warranty on every service. Based in Jacareí, São Paulo state, Brazil.',
    waText: 'Hello Valdir! I found the 4V Manutencoes website and need maintenance on a piece of equipment.',
    mailSubject: 'Quote – equipment maintenance',
    servicesLead: 'Corrective and preventive maintenance for hospitals, clinics, dental offices, laboratories, universities and city halls.',
    expTitle: 'Experience',
    expLead: 'Active since {since}, serving public universities and city halls.',
    expMore: 'See experience and main clients',
    faq: [FAQ_WARRANTY, FAQ_FREE, FAQ_PREVENTIVE, FAQ_PUBLIC, FAQ_QUOTE, FAQ_DOCS],
    areasTitle: 'Service areas',
    areasText: '4V Manutencoes is based in Jacareí and serves Jacareí, São José dos Campos, Caraguatatuba, Ubatuba and other cities in the Paraíba Valley and on the North Coast of São Paulo state.',
    areasMore: 'See service areas',
  },

  services: {
    autoclave: {
      slug: 'autoclave-maintenance',
      title: 'Autoclave Maintenance and Repair in Jacareí, Brazil | 4V',
      description: 'Repair and preventive maintenance of hospital, dental and laboratory autoclaves. Minimum 3-month warranty. Contact us on WhatsApp.',
      h1: 'Autoclave maintenance and repair',
      nav: 'Autoclaves',
      serviceName: 'Autoclave maintenance',
      card: 'Repair and preventive maintenance of hospital, dental and laboratory autoclaves.',
      waText: 'Hello Valdir! I found your website and need maintenance on an autoclave.',
      mailSubject: 'Quote – autoclave maintenance',
      intro: [
        'An autoclave sterilises instruments and materials with pressurised steam. When it stops, the dental office, clinic or laboratory stops with it. 4V Manutencoes repairs and services hospital, dental and laboratory autoclaves in Jacareí, São José dos Campos and the surrounding region.',
        'Service starts on WhatsApp: tell us the autoclave, brand, model and what is happening. The equipment is assessed, the work is done and tested, and you get the autoclave back with a written warranty certificate and usage instructions.',
        'In 2021, 4V Manutencoes repaired 3 autoclaves for the City of Ubatuba.',
      ],
      problems: [
        'Autoclave does not heat up or takes too long',
        'Autoclave does not build pressure or loses pressure during the cycle',
        'Steam leaking from the door',
        'Door gasket replacement',
        'Faulty safety or relief valve',
        'Cycle that never ends, stops halfway or shows an error',
        'Load comes out wet at the end of the cycle',
        'Dental, hospital and laboratory autoclave maintenance',
      ],
      sections: [
        { h2: 'Corrective and preventive maintenance', paras: [
          'Corrective maintenance fixes a fault that has already appeared: an autoclave that will not switch on, heat, build pressure or that leaks steam. The problem is assessed and explained before any part is replaced.',
          'Preventive maintenance checks the autoclave before it fails: cleaning and inspection of the gasket, valves, heating element and sensors, with worn items pointed out. This lowers the risk of interrupting your work and helps the equipment last longer.',
        ] },
      ],
      faq: [
        { q: 'My autoclave is not building pressure. What could it be?', a: 'The most common causes are a worn door gasket, a faulty valve, the heating element or a sensor. Only a technical assessment can confirm the cause. Message us on WhatsApp and describe what is happening.' },
        { q: 'Do you service dental autoclaves?', a: 'Yes. 4V Manutencoes services dental, hospital and laboratory autoclaves.' },
        FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['odonto', 'hospitalar'],
    },

    odonto: {
      slug: 'dental-equipment-maintenance',
      title: 'Dental Chair and Dental Unit Maintenance | 4V',
      description: 'Repair of dental units, spittoons, air/water syringes, high-speed handpieces and micromotors. Preventive maintenance. Written warranty.',
      h1: 'Dental equipment maintenance',
      nav: 'Dental equipment',
      serviceName: 'Dental equipment maintenance',
      card: 'Dental chairs and units, spittoons, air/water syringes, handpieces and micromotors.',
      waText: 'Hello Valdir! I found your website and need maintenance on dental equipment.',
      mailSubject: 'Quote – dental equipment maintenance',
      intro: [
        'In a dental office, a broken dental unit means rescheduled patients. 4V Manutencoes does corrective and preventive maintenance of dental chairs and units: delivery unit, spittoon, air/water syringe, hoses, high-speed handpiece and micromotor.',
        'You deal directly with the technician. Tell us on WhatsApp what the equipment is and what the problem is; the work is agreed, done and tested, and you receive the warranty certificate and usage instructions in writing.',
        '4V Manutencoes also services dental autoclaves, which usually work next to the dental unit in the same office.',
      ],
      problems: [
        'Dental unit without water or air, or with weak pressure',
        'Dried-out or leaking unit or spittoon hoses',
        'Spittoon that does not drain or fill the cup',
        'Air/water syringe without water or air',
        'High-speed handpiece or micromotor losing power or making noise',
        'Weak saliva ejector suction',
        'Chair controls that do not respond',
      ],
      sections: [
        { h2: 'Corrective and preventive maintenance in your office', paras: [
          'In corrective maintenance the fault is assessed and repaired, replacing the parts needed, such as hoses, fittings and dental unit or spittoon components.',
          'In preventive maintenance the equipment is checked before it fails: hoses, fittings, the water and air circuits and the controls. You also get simple daily-care instructions, such as cleaning the spittoon and draining the compressor.',
        ] },
      ],
      faq: [
        { q: 'Do you replace dental unit and spittoon hoses?', a: 'Yes. Replacing dental unit and spittoon hoses is one of the services included in dental equipment maintenance.' },
        { q: 'Which brands do you service?', a: 'Message us on WhatsApp with the brand and model of the equipment, so Valdir can confirm before booking the service.' },
        FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['autoclave', 'hospitalar'],
    },

    estufa: {
      slug: 'laboratory-oven-maintenance',
      title: 'Laboratory and Drying Oven Maintenance | 4V',
      description: 'Corrective and preventive maintenance of laboratory, drying and sterilising ovens. Minimum 3-month warranty on every service.',
      h1: 'Laboratory oven maintenance',
      nav: 'Lab ovens',
      serviceName: 'Laboratory oven maintenance',
      card: 'Laboratory, drying and sterilising ovens.',
      waText: 'Hello Valdir! I found your website and need maintenance on a laboratory oven.',
      mailSubject: 'Quote – laboratory oven maintenance',
      intro: [
        'Laboratory, drying and sterilising ovens must hold the right temperature for the work to succeed. When the oven does not heat, overshoots or switches itself off, the process is compromised.',
        '4V Manutencoes does corrective and preventive maintenance of ovens for university, clinic, hospital and company laboratories. The fault is assessed, the repair is done and tested, and you receive the warranty certificate and usage instructions in writing.',
      ],
      problems: [
        'Oven does not heat',
        'Temperature that does not stabilise or overshoots the set point',
        'Faulty thermostat or temperature controller',
        'Burnt-out heating element',
        'Internal fan not working',
        'Door that does not seal properly',
        'Oven that trips the breaker or switches itself off',
      ],
      sections: [
        { h2: 'Corrective and preventive maintenance', paras: [
          'In corrective maintenance the heating element, thermostat or controller, sensors, fan and wiring are checked and faulty parts are replaced.',
          'In preventive maintenance the oven is checked to avoid breakdowns: cleaning, door seal, electrical connections and the temperature control.',
        ] },
      ],
      faq: [
        { q: 'My oven does not heat. What could it be?', a: 'It may be the heating element, the thermostat or controller, a sensor or the power supply. Only a technical assessment can confirm the cause. Message us on WhatsApp and describe what happens.' },
        FAQ_PREVENTIVE, FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['capela', 'remanejamento'],
    },

    capela: {
      slug: 'fume-hood-maintenance',
      title: 'Fume Hood and Gas Exhaust Cabinet Maintenance | 4V',
      description: 'Maintenance of fume hoods and gas exhaust cabinets for laboratories and universities. Corrective and preventive, with warranty.',
      h1: 'Fume hood maintenance',
      nav: 'Fume hoods',
      serviceName: 'Fume hood maintenance',
      card: 'Chemical fume hoods and gas exhaust cabinets for laboratories.',
      waText: 'Hello Valdir! I found your website and need maintenance on a fume hood.',
      mailSubject: 'Quote – fume hood maintenance',
      intro: [
        'A fume hood (gas exhaust cabinet) protects laboratory staff by removing vapours and gases from the work area. To do that, the exhaust fan, ducts and sash must work properly.',
        '4V Manutencoes does corrective and preventive maintenance of chemical fume hoods and gas exhaust cabinets in university, school, hospital and company laboratories. The work is done, tested and delivered with a written warranty certificate and usage instructions.',
      ],
      problems: [
        'Exhaust fan that does not start or is noisy',
        'Weak extraction',
        'Sash that does not stay in place or does not slide',
        'Burnt-out interior light',
        'Faulty controls and switches',
        'Preventive check-ups of laboratory fume hoods',
      ],
      sections: [
        { h2: 'Corrective and preventive maintenance', paras: [
          'In corrective maintenance the fault in the fan, sash, lighting or controls is assessed and repaired.',
          'In preventive maintenance the hood is checked so it keeps protecting its users: fan, sash, wiring and cleaning. You also get usage guidance, such as working with the sash at the recommended height and not storing products inside the cabinet.',
        ] },
      ],
      faq: [
        { q: 'The fume hood has weak extraction. What could it be?', a: 'It may be the exhaust fan, a blockage in the openings or ducts, or an electrical problem. Only a technical assessment can confirm the cause.' },
        FAQ_PUBLIC, FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['bio', 'estufa'],
    },

    bio: {
      slug: 'biosafety-cabinet-maintenance',
      title: 'Biological Safety Cabinet Maintenance | 4V',
      description: 'Maintenance of biological safety cabinets and biosafety equipment for laboratories. Written warranty.',
      h1: 'Biological safety cabinet maintenance',
      nav: 'Biosafety',
      serviceName: 'Biological safety cabinet maintenance',
      card: 'Biological safety cabinets and biosafety equipment.',
      waText: 'Hello Valdir! I found your website and need maintenance on a biological safety cabinet.',
      mailSubject: 'Quote – biological safety cabinet maintenance',
      intro: [
        'A biological safety cabinet protects the operator, the material and the laboratory environment. It relies on the fan, clear grilles, lighting and controls to work safely.',
        '4V Manutencoes does corrective and preventive maintenance of biological safety cabinets and other biosafety equipment for laboratories. The work is done, tested and delivered with a written warranty certificate and usage instructions.',
      ],
      problems: [
        'Cabinet that does not switch on',
        'Noisy fan or weak airflow',
        'Burnt-out UV lamp or lighting',
        'Faulty controls, alarms or switches',
        'Preventive check-ups of biosafety equipment',
      ],
      sections: [
        { h2: 'Corrective and preventive maintenance', paras: [
          'In corrective maintenance the fault is assessed and repaired, replacing the parts needed.',
          'In preventive maintenance the cabinet is checked before it fails, and usage guidance is reinforced: wait for the stabilisation time, do not block the grilles and never use the UV lamp with the operator present. Follow the maintenance interval set by the manufacturer.',
        ] },
      ],
      faq: [
        { q: 'How often does the cabinet need preventive maintenance?', a: 'Follow the interval set by the manufacturer and your laboratory protocol. 4V Manutencoes can carry out the check-ups at that interval.' },
        FAQ_PUBLIC, FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['capela', 'remanejamento'],
    },

    hospitalar: {
      slug: 'hospital-equipment-maintenance',
      title: 'Medical and Hospital Equipment Maintenance | 4V',
      description: 'Maintenance of autoclaves, vacuum pumps, cardioverters and hospital equipment. Experience with the public sector and universities.',
      h1: 'Medical and hospital equipment maintenance',
      nav: 'Hospital equipment',
      serviceName: 'Medical and hospital equipment maintenance',
      card: 'Autoclaves, vacuum pumps, cardioverters and other equipment.',
      waText: 'Hello Valdir! I found your website and need maintenance on hospital equipment.',
      mailSubject: 'Quote – hospital equipment maintenance',
      intro: [
        'Hospitals, clinics and health units depend on equipment that works every day. 4V Manutencoes does corrective and preventive maintenance of medical and hospital equipment such as autoclaves, vacuum pumps and cardioverters.',
        'The company has public-sector experience: in 2018 it serviced a cardioverter under a public contract, and in 2021 it repaired 3 autoclaves for the City of Ubatuba. It also serves public universities such as USP, UNESP and Unifesp.',
      ],
      problems: [
        'Autoclave that does not heat, build pressure or that leaks steam',
        'Vacuum pump with no suction or making noise',
        'Cardioverter maintenance',
        'Equipment that does not switch on or trips',
        'Preventive check-ups of hospital equipment',
      ],
      sections: [
        { h2: 'Corrective and preventive maintenance', paras: [
          'In corrective maintenance the broken equipment is assessed, the fault is explained and the repair is done and tested before delivery.',
          'In preventive maintenance equipment is checked before it fails, lowering the risk of interrupting care and helping extend its service life.',
        ] },
        { h2: 'Paperwork for public procurement', paras: [
          'Every service comes with a written warranty certificate showing the document number, the work done, the parts replaced and the warranty term. This makes it easier for city halls, universities and hospitals to record the service.',
        ] },
      ],
      faq: [FAQ_PUBLIC, FAQ_DOCS, FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE],
      related: ['autoclave', 'remanejamento'],
    },

    remanejamento: {
      slug: 'laboratory-equipment-installation-and-relocation',
      title: 'Laboratory Equipment Installation and Relocation | 4V',
      description: 'Uninstalling, moving and reinstalling laboratory equipment. Experience with USP, UNESP and Unifesp.',
      h1: 'Laboratory equipment installation and relocation',
      nav: 'Lab relocation',
      serviceName: 'Laboratory equipment installation and relocation',
      card: 'Uninstalling, moving and reinstalling laboratory equipment.',
      waText: 'Hello Valdir! I found your website and need laboratory equipment installed or relocated.',
      mailSubject: 'Quote – laboratory equipment relocation',
      intro: [
        'Moving a laboratory to another room or building takes care: equipment must be switched off and uninstalled correctly, moved and reinstalled in working order.',
        '4V Manutencoes uninstalls, relocates and reinstalls laboratory equipment. In 2024 it did this work for UNESP. The company has experience with laboratories at public universities such as USP, UNESP and Unifesp.',
      ],
      problems: [
        'Uninstalling laboratory equipment',
        'Moving a laboratory to another room or building',
        'Reinstalling and testing after the move',
        'Installing laboratory equipment',
        'Servicing the equipment during the move',
      ],
      sections: [
        { h2: 'Equipment that usually moves together', paras: [
          'A laboratory move usually includes equipment such as ovens, fume hoods, biological safety cabinets, autoclaves and vacuum pumps. These are the same types of equipment 4V Manutencoes maintains, which helps reinstall each one correctly and check that it works after the move.',
          'Send the list of equipment, the origin and destination addresses and the deadline for the move. That way the quote comes faster and the work can be planned with the laboratory.',
        ] },
        { h2: 'How the work is done', list: [
          'Survey of the equipment to be moved and of the destination.',
          'Careful shutdown and uninstallation.',
          'Relocation to the new site.',
          'Reinstallation, functional testing and handover with a written document.',
        ] },
      ],
      faq: [
        FAQ_PUBLIC,
        { q: 'Can the equipment be serviced during the move?', a: 'Yes. A move is a good moment for preventive maintenance. Include the equipment list when you ask for a quote.' },
        FAQ_DOCS, FAQ_QUOTE,
      ],
      related: ['estufa', 'capela'],
    },
  },

  experiencia: {
    slug: 'experience',
    title: 'Experience and Clients: USP, UNESP, Unifesp | 4V Manutencoes',
    description: 'Serving public universities and city halls since 2015. Learn about the experience of 4V Manutencoes.',
    h1: 'Experience and main clients',
    nav: 'Experience',
    waText: 'Hello Valdir! I found the 4V Manutencoes website and would like a quote.',
    mailSubject: 'Quote – 4V Manutencoes',
    lead: '4V Manutencoes has been active since {since}, maintaining medical, hospital, laboratory and dental equipment.',
    sinceLabel: 'Since',
    uniTitle: 'Main clients: universities',
    uniLead: 'Experience with three of Brazil’s largest public universities.',
    unis: [['USP', 'University of São Paulo'], ['UNESP', 'São Paulo State University “Júlio de Mesquita Filho”'], ['Unifesp', 'Federal University of São Paulo']],
    publicTitle: 'Public-sector work',
    publicItems: [
      ['2018', 'Cardioverter maintenance (public contract).'],
      ['2021', 'City of Ubatuba: repair of 3 autoclaves.'],
      ['2024', 'UNESP: uninstalling, relocating and reinstalling laboratory equipment.'],
    ],
    eqTitle: 'Equipment experience',
    equipment: ['Autoclaves', 'Vacuum pumps', 'Cardioverters', 'Laboratory equipment', 'Dental equipment', 'Laboratory ovens', 'Fume hoods', 'Biosafety equipment'],
    otherTitle: 'More about the company',
    other: [
      'In 2016 it repaired a Dabi Atlante dental unit and spittoon.',
      'Listed by Prismatec as a technical service provider in Jacareí.',
      'Civic involvement: member of the Jacareí Municipal Council for the Rights of Persons with Disabilities (2019–2021).',
    ],
    note: 'University names are mentioned only to show service experience.',
  },

  areas: {
    slug: 'service-areas',
    title: 'Service Areas: Jacareí, São José dos Campos and Region | 4V',
    description: 'Medical and laboratory equipment maintenance in Jacareí, the Paraíba Valley and the North Coast of São Paulo state, Brazil.',
    h1: 'Service areas',
    nav: 'Service areas',
    waText: 'Hello Valdir! I found your website and would like to know if you cover my city.',
    mailSubject: 'Quote – service in my city',
    paras: [
      '4V Manutencoes is based in Jacareí, in the Paraíba Valley, and maintains medical, laboratory and dental equipment in the city and the surrounding region.',
      'It has served clients in Jacareí, São José dos Campos, Caraguatatuba and Ubatuba, including autoclave repairs for the City of Ubatuba. It also has experience with laboratories at public universities such as USP, UNESP and Unifesp.',
      'To check whether your city is covered, message us on WhatsApp with the city, the equipment and the problem.',
    ],
    citiesTitle: 'Cities already served',
    cities: ['Jacareí', 'São José dos Campos', 'Caraguatatuba', 'Ubatuba'],
    regionsTitle: 'Regions',
    regions: ['Paraíba Valley (Vale do Paraíba)', 'North Coast of São Paulo state (Litoral Norte)'],
    outside: 'In another city? Ask us on WhatsApp.',
  },

  contato: {
    slug: 'contact',
    title: 'Contact: WhatsApp and E-mail | 4V Manutencoes',
    description: 'Message us on WhatsApp {phone} or e-mail {email}. Quote request form. Jacareí, São Paulo state, Brazil.',
    h1: 'Contact 4V Manutencoes',
    nav: 'Contact',
    waText: 'Hello Valdir! I found the 4V Manutencoes website and would like a quote.',
    mailSubject: 'Quote – 4V Manutencoes',
    lead: 'WhatsApp is the fastest way. You can also send an e-mail or use the form below.',
    tipsTitle: 'To speed up your quote, tell us:',
    tips: ['The equipment, brand and model.', 'What is happening.', 'The city where the equipment is.', 'If you can, a photo of the equipment label.'],
  },

  obrigado: {
    slug: 'thank-you',
    title: 'Message sent | 4V Manutencoes',
    description: 'Your message was sent to 4V Manutencoes.',
    h1: 'Message sent',
    nav: 'Message sent',
    waText: 'Hello Valdir! I just sent a message through the 4V Manutencoes website.',
    mailSubject: 'Quote – 4V Manutencoes',
    lead: 'Message sent. Valdir will reply by e-mail or WhatsApp.',
    back: 'Back to home',
  },

  notfound: {
    slug: '404',
    title: 'Page not found | 4V Manutencoes',
    description: 'This page does not exist.',
    h1: 'Page not found',
    nav: 'Page not found',
    waText: 'Hello Valdir! I found the 4V Manutencoes website and need maintenance on a piece of equipment.',
    mailSubject: 'Quote – 4V Manutencoes',
    lead: 'This page does not exist or has moved.',
    back: 'Go to the home page',
  },
};
