import type { Content, Faq } from './types';

const FAQ_WARRANTY: Faq = { q: 'Quelle est la durée de garantie du service ?', a: 'Tous les services ont une garantie minimale de 3 mois, indiquée par écrit dans le certificat de garantie. Selon le service, la durée peut être plus longue.' };
const FAQ_FREE: Faq = { q: 'L’intervention sous garantie est-elle payante ?', a: 'Non. L’intervention sous garantie est gratuite pour le client.' };
const FAQ_PREVENTIVE: Faq = { q: 'Faites-vous de la maintenance préventive ?', a: 'Oui. La maintenance préventive contrôle l’équipement avant la panne, ce qui réduit le risque d’interrompre votre activité et prolonge sa durée de vie.' };
const FAQ_PUBLIC: Faq = { q: 'Intervenez-vous pour des universités et des organismes publics ?', a: 'Oui. 4V Manutencoes a déjà travaillé pour l’USP, l’UNESP, l’Unifesp et des mairies de la région.' };
const FAQ_QUOTE: Faq = { q: 'Comment demander un devis ?', a: 'Écrivez sur WhatsApp au {phone}, envoyez un e-mail à {email} ou utilisez le formulaire de contact. Indiquez l’équipement, la marque et le modèle, et décrivez le problème. Si possible, envoyez une photo de la plaque signalétique.' };
const FAQ_DOCS: Faq = { q: 'Est-ce que je reçois un document pour le service ?', a: 'Oui. Vous recevez par écrit le certificat de garantie et les consignes d’utilisation de l’équipement.' };

export const fr: Content = {
  ui: {
    htmlLang: 'fr', ogLocale: 'fr_FR', langName: 'Français',
    skip: 'Aller au contenu', menu: 'Menu', home: 'Accueil',
    waBtn: 'Écrire sur WhatsApp', mailBtn: 'Envoyer un e-mail', callBtn: 'Appeler',
    phoneLabel: 'WhatsApp et téléphone', emailLabel: 'E-mail', addressLabel: 'Adresse', cnpjLabel: 'CNPJ (n° d’entreprise)',
    servicesTitle: 'Services', problemsTitle: 'Pannes courantes que nous réparons', faqTitle: 'Questions fréquentes',
    relatedTitle: 'Autres services', seeExperience: 'Voir l’expérience de 4V Manutencoes',
    warrantyTitle: 'Garantie écrite',
    warrantySeal: ['GARANTIE MINIMALE', '3', 'MOIS', 'SUR TOUS LES SERVICES'],
    warrantyPoints: [
      'Garantie minimale de 3 mois sur tous les services. Selon le service, la durée peut être plus longue.',
      'L’intervention sous garantie est gratuite pour le client.',
      'Vous recevez par écrit le certificat de garantie et les consignes d’utilisation de l’équipement.',
    ],
    contactTitle: 'Demander un devis',
    contactLead: 'Parlez directement avec Valdir. Indiquez l’équipement, la marque, le modèle et le problème.',
    howTitle: 'Comment ça marche',
    howSteps: [
      'Écrivez sur WhatsApp ou envoyez un e-mail en décrivant l’équipement et le problème.',
      'L’équipement est évalué.',
      'L’intervention est réalisée et testée.',
      'Vous récupérez l’équipement avec un certificat de garantie et les consignes d’utilisation.',
    ],
    areasLine: 'Interventions à São Paulo et dans le Grand São Paulo, à Jacareí, São José dos Campos, dans la vallée du Paraíba et sur le littoral nord de l’État de São Paulo (Brésil).',
    langSwitch: 'Langue',
    footerServices: 'Services', footerAbout: 'L’entreprise',
    form: {
      title: 'Formulaire de demande de devis',
      lead: 'Remplissez ce que vous savez. Valdir répondra par e-mail ou sur WhatsApp.',
      name: 'Nom', org: 'Entreprise ou établissement', city: 'Ville', phone: 'Téléphone ou WhatsApp', email: 'E-mail',
      equipment: 'Équipement (marque et modèle)', equipmentHint: 'Ex. : autoclave Cristófoli 21 litres', message: 'Message',
      send: 'Envoyer le message', required: 'obligatoire',
      tooFast: 'Vérifiez vos informations et touchez « Envoyer le message » à nouveau.',
      subject: 'Demande de devis depuis le site (FR)',
    },
    portraitAlt: 'Valdir de Paula Bicudo, technicien de 4V Manutencoes',
    logoAlt: '4V Manutencoes',
    vcard: 'Enregistrer le contact sur votre téléphone (vCard)',
    photoCaptionTitle: 'Valdir Bicudo',
    photoCaption: 'Parlez directement avec Valdir sur WhatsApp.',
  },

  home: {
    slug: '',
    title: 'Maintenance d’équipements médicaux et de laboratoire | 4V',
    description: 'Maintenance corrective et préventive d’autoclaves, d’étuves, de sorbonnes et d’équipements dentaires à Jacareí (Brésil). Garantie écrite.',
    h1: 'Maintenance d’équipements médicaux, de laboratoire et dentaires',
    nav: 'Accueil',
    eyebrow: 'Assistance technique spécialisée',
    lead: 'Maintenance corrective et préventive, avec une garantie écrite sur tous les services. Interventions dans le Grand São Paulo et la vallée du Paraíba (Brésil).',
    waText: 'Bonjour Valdir ! J’ai trouvé le site de 4V Manutencoes et j’ai besoin d’une maintenance sur un équipement.',
    mailSubject: 'Devis – maintenance d’équipement',
    servicesLead: 'Maintenance corrective et préventive pour hôpitaux, cliniques, cabinets dentaires, laboratoires, universités et mairies.',
    expTitle: 'Expérience',
    expLead: 'En activité depuis {since}, au service d’universités publiques et de mairies.',
    expMore: 'Voir l’expérience et les principaux clients',
    faq: [FAQ_WARRANTY, FAQ_FREE, FAQ_PREVENTIVE, FAQ_PUBLIC, FAQ_QUOTE, FAQ_DOCS],
    areasTitle: 'Zones desservies',
    areasText: '4V Manutencoes est basé à Jacareí et intervient à São Paulo et dans le Grand São Paulo, ainsi qu’à Jacareí, São José dos Campos, Caraguatatuba, Ubatuba et dans d’autres villes de la vallée du Paraíba et du littoral nord de l’État de São Paulo.',
    areasMore: 'Voir les zones desservies',
  },

  services: {
    autoclave: {
      slug: 'maintenance-autoclave',
      title: 'Maintenance et réparation d’autoclaves à Jacareí | 4V',
      description: 'Réparation et maintenance préventive d’autoclaves hospitaliers, dentaires et de laboratoire. Garantie minimale de 3 mois. Contact par WhatsApp.',
      h1: 'Maintenance et réparation d’autoclaves',
      nav: 'Autoclaves',
      serviceName: 'Maintenance d’autoclaves',
      card: 'Réparation et maintenance préventive d’autoclaves hospitaliers, dentaires et de laboratoire.',
      waText: 'Bonjour Valdir ! J’ai trouvé votre site et j’ai besoin d’une maintenance sur un autoclave.',
      mailSubject: 'Devis – maintenance d’autoclave',
      intro: [
        'L’autoclave stérilise les instruments et le matériel à la vapeur sous pression. Quand il s’arrête, le cabinet, la clinique ou le laboratoire s’arrête aussi. 4V Manutencoes répare et entretient les autoclaves hospitaliers, dentaires et de laboratoire à Jacareí, São José dos Campos et dans la région.',
        'Tout commence sur WhatsApp : indiquez l’autoclave, la marque, le modèle et ce qui se passe. L’équipement est évalué, l’intervention est réalisée et testée, et vous récupérez l’autoclave avec un certificat de garantie et des consignes d’utilisation écrits.',
        'En 2021, 4V Manutencoes a réparé 3 autoclaves pour la mairie d’Ubatuba.',
      ],
      problems: [
        'Autoclave qui ne chauffe pas ou chauffe trop lentement',
        'Autoclave qui ne monte pas en pression ou perd la pression pendant le cycle',
        'Fuite de vapeur par la porte',
        'Remplacement du joint de porte',
        'Soupape de sécurité ou de décharge défectueuse',
        'Cycle qui ne se termine pas, s’arrête au milieu ou affiche une erreur',
        'Charge mouillée en fin de cycle',
        'Maintenance d’autoclaves dentaires, hospitaliers et de laboratoire',
      ],
      sections: [
        { h2: 'Maintenance corrective et préventive', paras: [
          'La maintenance corrective résout une panne déjà présente : autoclave qui ne s’allume pas, ne chauffe pas, ne monte pas en pression ou fuit. Le problème est évalué et expliqué avant tout remplacement de pièce.',
          'La maintenance préventive contrôle l’autoclave avant la panne : nettoyage, vérification du joint, des soupapes, de la résistance et des capteurs, avec indication des pièces usées. Cela réduit le risque d’interrompre votre activité et aide l’équipement à durer plus longtemps.',
        ] },
      ],
      faq: [
        { q: 'Mon autoclave ne monte pas en pression. Qu’est-ce que cela peut être ?', a: 'Les causes les plus fréquentes sont un joint de porte usé, une soupape défectueuse, la résistance ou un capteur. Seule une évaluation technique permet de confirmer la cause. Écrivez sur WhatsApp en décrivant ce qui se passe.' },
        { q: 'Intervenez-vous sur les autoclaves dentaires ?', a: 'Oui. 4V Manutencoes assure la maintenance d’autoclaves dentaires, hospitaliers et de laboratoire.' },
        FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['odonto', 'hospitalar'],
    },

    odonto: {
      slug: 'maintenance-equipements-dentaires',
      title: 'Maintenance de fauteuils et d’units dentaires | 4V',
      description: 'Réparation d’units dentaires, crachoirs, seringues air-eau, turbines et micromoteurs. Maintenance préventive. Garantie écrite.',
      h1: 'Maintenance d’équipements dentaires',
      nav: 'Équipements dentaires',
      serviceName: 'Maintenance d’équipements dentaires',
      card: 'Fauteuils et units dentaires, crachoirs, seringues air-eau, turbines et micromoteurs.',
      waText: 'Bonjour Valdir ! J’ai trouvé votre site et j’ai besoin d’une maintenance sur un équipement dentaire.',
      mailSubject: 'Devis – maintenance d’équipement dentaire',
      intro: [
        'Dans un cabinet dentaire, un unit en panne signifie des patients à reprogrammer. 4V Manutencoes assure la maintenance corrective et préventive des fauteuils et units dentaires : unit, crachoir, seringue air-eau, tuyaux, turbine et micromoteur.',
        'Vous traitez directement avec le technicien. Indiquez sur WhatsApp l’équipement et le problème ; l’intervention est convenue, réalisée et testée, et vous recevez par écrit le certificat de garantie et les consignes d’utilisation.',
        '4V Manutencoes entretient aussi les autoclaves dentaires, qui travaillent souvent à côté de l’unit dans le même cabinet.',
      ],
      problems: [
        'Unit sans eau ou sans air, ou avec une pression faible',
        'Tuyaux de l’unit ou du crachoir desséchés ou qui fuient',
        'Crachoir qui ne s’évacue pas ou ne remplit pas le gobelet',
        'Seringue air-eau sans eau ou sans air',
        'Turbine ou micromoteur qui perd de la puissance ou fait du bruit',
        'Aspiration faible',
        'Commandes du fauteuil qui ne répondent pas',
      ],
      sections: [
        { h2: 'Maintenance corrective et préventive au cabinet', paras: [
          'En maintenance corrective, la panne est évaluée et réparée, avec le remplacement des pièces nécessaires, comme les tuyaux, les raccords et les composants de l’unit ou du crachoir.',
          'En maintenance préventive, l’équipement est contrôlé avant la panne : tuyaux, raccords, circuits d’eau et d’air et commandes. Vous recevez aussi des consignes d’entretien quotidien simples, comme le nettoyage du crachoir et la purge du compresseur.',
        ] },
      ],
      faq: [
        { q: 'Remplacez-vous les tuyaux de l’unit et du crachoir ?', a: 'Oui. Le remplacement des tuyaux de l’unit et du crachoir fait partie de la maintenance des équipements dentaires.' },
        { q: 'Quelles marques prenez-vous en charge ?', a: 'Écrivez sur WhatsApp en indiquant la marque et le modèle de l’équipement, pour que Valdir confirme avant de planifier l’intervention.' },
        FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['autoclave', 'hospitalar'],
    },

    estufa: {
      slug: 'maintenance-etuve-de-laboratoire',
      title: 'Maintenance d’étuves de laboratoire et de séchage | 4V',
      description: 'Maintenance corrective et préventive d’étuves de laboratoire, de séchage et de stérilisation. Garantie minimale de 3 mois.',
      h1: 'Maintenance d’étuves de laboratoire',
      nav: 'Étuves',
      serviceName: 'Maintenance d’étuves de laboratoire',
      card: 'Étuves de laboratoire, de séchage et de stérilisation.',
      waText: 'Bonjour Valdir ! J’ai trouvé votre site et j’ai besoin d’une maintenance sur une étuve.',
      mailSubject: 'Devis – maintenance d’étuve',
      intro: [
        'Les étuves de laboratoire, de séchage et de stérilisation doivent maintenir la bonne température pour que le travail aboutisse. Quand l’étuve ne chauffe pas, dépasse la consigne ou s’éteint toute seule, le processus est compromis.',
        '4V Manutencoes assure la maintenance corrective et préventive d’étuves pour les laboratoires d’universités, de cliniques, d’hôpitaux et d’entreprises. La panne est évaluée, la réparation est réalisée et testée, et vous recevez par écrit le certificat de garantie et les consignes d’utilisation.',
      ],
      problems: [
        'Étuve qui ne chauffe pas',
        'Température qui ne se stabilise pas ou dépasse la consigne',
        'Thermostat ou régulateur de température défectueux',
        'Résistance grillée',
        'Ventilation intérieure en panne',
        'Porte qui ne ferme pas hermétiquement',
        'Étuve qui fait disjoncter ou s’éteint toute seule',
      ],
      sections: [
        { h2: 'Maintenance corrective et préventive', paras: [
          'En maintenance corrective, la résistance, le thermostat ou régulateur, les capteurs, la ventilation et la partie électrique sont vérifiés, et les pièces défectueuses sont remplacées.',
          'En maintenance préventive, l’étuve est contrôlée pour éviter les arrêts : nettoyage, joint de porte, connexions électriques et régulation de température.',
        ] },
      ],
      faq: [
        { q: 'Mon étuve ne chauffe pas. Qu’est-ce que cela peut être ?', a: 'Il peut s’agir de la résistance, du thermostat ou régulateur, d’un capteur ou de l’alimentation électrique. Seule une évaluation technique permet de confirmer la cause. Écrivez sur WhatsApp en décrivant ce qui se passe.' },
        FAQ_PREVENTIVE, FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['capela', 'remanejamento'],
    },

    capela: {
      slug: 'maintenance-sorbonne',
      title: 'Maintenance de sorbonnes et hottes d’extraction | 4V',
      description: 'Maintenance de sorbonnes et de hottes d’extraction de gaz pour laboratoires et universités. Corrective et préventive, avec garantie.',
      h1: 'Maintenance de sorbonnes (hottes d’extraction de gaz)',
      nav: 'Sorbonnes',
      serviceName: 'Maintenance de sorbonnes',
      card: 'Sorbonnes de chimie et hottes d’extraction de gaz pour laboratoires.',
      waText: 'Bonjour Valdir ! J’ai trouvé votre site et j’ai besoin d’une maintenance sur une sorbonne.',
      mailSubject: 'Devis – maintenance de sorbonne',
      intro: [
        'La sorbonne (hotte d’extraction de gaz) protège le personnel du laboratoire en évacuant les vapeurs et les gaz de la zone de travail. Pour cela, l’extracteur, les conduits et la vitre doivent bien fonctionner.',
        '4V Manutencoes assure la maintenance corrective et préventive de sorbonnes de chimie et de hottes d’extraction de gaz dans les laboratoires d’universités, d’écoles, d’hôpitaux et d’entreprises. L’intervention est réalisée, testée et livrée avec un certificat de garantie et des consignes d’utilisation écrits.',
      ],
      problems: [
        'Extracteur qui ne démarre pas ou fait du bruit',
        'Aspiration faible',
        'Vitre (guillotine) qui ne tient pas en position ou ne coulisse pas',
        'Éclairage intérieur grillé',
        'Commandes et interrupteurs défectueux',
        'Contrôles préventifs de sorbonnes de laboratoire',
      ],
      sections: [
        { h2: 'Maintenance corrective et préventive', paras: [
          'En maintenance corrective, la panne de l’extracteur, de la vitre, de l’éclairage ou des commandes est évaluée et réparée.',
          'En maintenance préventive, la sorbonne est contrôlée pour continuer à protéger ses utilisateurs : extracteur, vitre, partie électrique et nettoyage. Vous recevez aussi des consignes, comme travailler avec la vitre à la hauteur indiquée et ne pas stocker de produits dans la hotte.',
        ] },
      ],
      faq: [
        { q: 'La sorbonne aspire mal. Qu’est-ce que cela peut être ?', a: 'Il peut s’agir de l’extracteur, d’une obstruction des ouvertures ou des conduits, ou d’un problème électrique. Seule une évaluation technique permet de confirmer la cause.' },
        FAQ_PUBLIC, FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['bio', 'estufa'],
    },

    bio: {
      slug: 'maintenance-poste-securite-microbiologique',
      title: 'Maintenance de postes de sécurité microbiologique | 4V',
      description: 'Maintenance de postes de sécurité microbiologique et d’équipements de biosécurité pour laboratoires. Garantie écrite.',
      h1: 'Maintenance de postes de sécurité microbiologique',
      nav: 'Biosécurité',
      serviceName: 'Maintenance de postes de sécurité microbiologique',
      card: 'Postes de sécurité microbiologique et équipements de biosécurité.',
      waText: 'Bonjour Valdir ! J’ai trouvé votre site et j’ai besoin d’une maintenance sur un poste de sécurité microbiologique.',
      mailSubject: 'Devis – maintenance de PSM',
      intro: [
        'Le poste de sécurité microbiologique protège l’opérateur, le matériel et l’environnement du laboratoire. Il dépend du ventilateur, de grilles dégagées, de l’éclairage et des commandes pour fonctionner en sécurité.',
        '4V Manutencoes assure la maintenance corrective et préventive des postes de sécurité microbiologique et d’autres équipements de biosécurité pour laboratoires. L’intervention est réalisée, testée et livrée avec un certificat de garantie et des consignes d’utilisation écrits.',
      ],
      problems: [
        'Poste qui ne s’allume pas',
        'Ventilateur bruyant ou flux d’air faible',
        'Lampe UV ou éclairage grillé',
        'Commandes, alarmes ou interrupteurs défectueux',
        'Contrôles préventifs d’équipements de biosécurité',
      ],
      sections: [
        { h2: 'Maintenance corrective et préventive', paras: [
          'En maintenance corrective, la panne est évaluée et réparée, avec le remplacement des pièces nécessaires.',
          'En maintenance préventive, le poste est contrôlé avant la panne et les consignes d’utilisation sont rappelées : attendre le temps de stabilisation, ne pas obstruer les grilles et ne jamais utiliser la lampe UV en présence de l’opérateur. Respectez la périodicité de maintenance indiquée par le fabricant.',
        ] },
      ],
      faq: [
        { q: 'À quelle fréquence le poste doit-il être entretenu ?', a: 'Suivez la périodicité indiquée par le fabricant et le protocole de votre laboratoire. 4V Manutencoes peut réaliser les contrôles à cet intervalle.' },
        FAQ_PUBLIC, FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE,
      ],
      related: ['capela', 'remanejamento'],
    },

    hospitalar: {
      slug: 'maintenance-equipements-hospitaliers',
      title: 'Maintenance d’équipements médicaux et hospitaliers | 4V',
      description: 'Maintenance d’autoclaves, pompes à vide, cardioverteurs et équipements hospitaliers. Expérience avec le secteur public et les universités.',
      h1: 'Maintenance d’équipements médicaux et hospitaliers',
      nav: 'Équipements hospitaliers',
      serviceName: 'Maintenance d’équipements médicaux et hospitaliers',
      card: 'Autoclaves, pompes à vide, cardioverteurs et autres équipements.',
      waText: 'Bonjour Valdir ! J’ai trouvé votre site et j’ai besoin d’une maintenance sur un équipement hospitalier.',
      mailSubject: 'Devis – maintenance d’équipement hospitalier',
      intro: [
        'Les hôpitaux, cliniques et centres de santé dépendent d’équipements qui fonctionnent tous les jours. 4V Manutencoes assure la maintenance corrective et préventive d’équipements médicaux et hospitaliers comme les autoclaves, les pompes à vide et les cardioverteurs.',
        'L’entreprise a l’expérience du secteur public : en 2018, elle a assuré la maintenance d’un cardioverteur dans le cadre d’un marché public, et en 2021 elle a réparé 3 autoclaves pour la mairie d’Ubatuba. Elle travaille aussi pour des universités publiques comme l’USP, l’UNESP et l’Unifesp.',
      ],
      problems: [
        'Autoclave qui ne chauffe pas, ne monte pas en pression ou fuit',
        'Pompe à vide sans aspiration ou bruyante',
        'Maintenance de cardioverteurs',
        'Équipement qui ne s’allume pas ou fait disjoncter',
        'Contrôles préventifs d’équipements hospitaliers',
      ],
      sections: [
        { h2: 'Maintenance corrective et préventive', paras: [
          'En maintenance corrective, l’équipement en panne est évalué, la panne est expliquée et la réparation est réalisée et testée avant la livraison.',
          'En maintenance préventive, les équipements sont contrôlés avant la panne, ce qui réduit le risque d’interrompre les soins et aide à prolonger leur durée de vie.',
        ] },
        { h2: 'Documents pour les marchés publics', paras: [
          'Chaque intervention est accompagnée d’un certificat de garantie écrit indiquant le numéro du document, la description du travail, les pièces remplacées et la durée de garantie. Cela facilite l’enregistrement de l’intervention par les mairies, universités et hôpitaux.',
        ] },
      ],
      faq: [FAQ_PUBLIC, FAQ_DOCS, FAQ_WARRANTY, FAQ_FREE, FAQ_QUOTE],
      related: ['autoclave', 'remanejamento'],
    },

    remanejamento: {
      slug: 'installation-et-demenagement-equipements-de-laboratoire',
      title: 'Installation et déménagement d’équipements de laboratoire',
      description: 'Désinstallation, déménagement et réinstallation d’équipements de laboratoire. Expérience avec l’USP, l’UNESP et l’Unifesp.',
      h1: 'Installation et déménagement d’équipements de laboratoire',
      nav: 'Déménagement de labo',
      serviceName: 'Installation et déménagement d’équipements de laboratoire',
      card: 'Désinstallation, déménagement et réinstallation d’équipements de laboratoire.',
      waText: 'Bonjour Valdir ! J’ai trouvé votre site et j’ai besoin d’installer ou de déménager des équipements de laboratoire.',
      mailSubject: 'Devis – déménagement d’équipements de laboratoire',
      intro: [
        'Déménager un laboratoire dans une autre salle ou un autre bâtiment demande du soin : les équipements doivent être arrêtés et désinstallés correctement, transportés et réinstallés en état de marche.',
        '4V Manutencoes désinstalle, déménage et réinstalle les équipements de laboratoire. En 2024, elle a réalisé ce travail pour l’UNESP. L’entreprise a l’expérience des laboratoires d’universités publiques comme l’USP, l’UNESP et l’Unifesp.',
      ],
      problems: [
        'Désinstallation d’équipements de laboratoire',
        'Déménagement d’un laboratoire dans une autre salle ou un autre bâtiment',
        'Réinstallation et test de fonctionnement après le déménagement',
        'Installation d’équipements de laboratoire',
        'Entretien des équipements à l’occasion du déménagement',
      ],
      sections: [
        { h2: 'Les équipements qui déménagent ensemble', paras: [
          'Un déménagement de laboratoire comprend souvent des étuves, des sorbonnes, des postes de sécurité microbiologique, des autoclaves et des pompes à vide. Ce sont les mêmes types d’équipements que 4V Manutencoes entretient, ce qui aide à réinstaller chacun correctement et à vérifier son fonctionnement après le déménagement.',
          'Envoyez la liste des équipements, les adresses de départ et d’arrivée et la date limite du déménagement. Le devis sera plus rapide et le travail pourra être planifié avec le laboratoire.',
        ] },
        { h2: 'Déroulement de l’intervention', list: [
          'Relevé des équipements à déplacer et du lieu de destination.',
          'Arrêt et désinstallation avec soin.',
          'Transfert vers le nouveau lieu.',
          'Réinstallation, test de fonctionnement et remise avec un document écrit.',
        ] },
      ],
      faq: [
        FAQ_PUBLIC,
        { q: 'Peut-on entretenir les équipements pendant le déménagement ?', a: 'Oui. Un déménagement est un bon moment pour la maintenance préventive. Joignez la liste des équipements à votre demande de devis.' },
        FAQ_DOCS, FAQ_QUOTE,
      ],
      related: ['estufa', 'capela'],
    },
  },

  experiencia: {
    slug: 'experience',
    title: 'Expérience et clients : USP, UNESP, Unifesp | 4V Manutencoes',
    description: 'Au service d’universités publiques et de mairies depuis 2015. Découvrez l’expérience de 4V Manutencoes.',
    h1: 'Expérience et principaux clients',
    nav: 'Expérience',
    waText: 'Bonjour Valdir ! J’ai trouvé le site de 4V Manutencoes et je voudrais un devis.',
    mailSubject: 'Devis – 4V Manutencoes',
    lead: '4V Manutencoes est en activité depuis {since} et assure la maintenance d’équipements médicaux, hospitaliers, de laboratoire et dentaires.',
    sinceLabel: 'Depuis',
    uniTitle: 'Principaux clients : universités',
    uniLead: 'Une expérience auprès de trois des plus grandes universités publiques du Brésil.',
    unis: [['USP', 'Université de São Paulo'], ['UNESP', 'Université d’État de São Paulo « Júlio de Mesquita Filho »'], ['Unifesp', 'Université fédérale de São Paulo']],
    publicTitle: 'Interventions pour le secteur public',
    publicItems: [
      ['2018', 'Maintenance d’un cardioverteur (marché public).'],
      ['2021', 'Mairie d’Ubatuba : réparation de 3 autoclaves.'],
      ['2024', 'UNESP : désinstallation, déménagement et réinstallation d’équipements de laboratoire.'],
    ],
    eqTitle: 'Expérience par équipement',
    equipment: ['Autoclaves', 'Pompes à vide', 'Cardioverteurs', 'Équipements de laboratoire', 'Équipements dentaires', 'Étuves', 'Sorbonnes', 'Équipements de biosécurité'],
    otherTitle: 'En savoir plus sur l’entreprise',
    other: [
      'En 2016, réparation d’un unit et d’un crachoir dentaires Dabi Atlante.',
      'Référencée par Prismatec comme service d’assistance technique à Jacareí.',
      'Engagement institutionnel : membre du Conseil municipal des droits des personnes handicapées de Jacareí (2019–2021).',
    ],
    note: 'Les noms des universités sont cités uniquement pour indiquer l’expérience d’intervention.',
  },

  areas: {
    slug: 'zones-desservies',
    title: 'Zones desservies : Grand São Paulo et vallée du Paraíba | 4V',
    description: 'Maintenance d’équipements médicaux et de laboratoire à São Paulo, dans le Grand São Paulo, à Jacareí et dans la vallée du Paraíba.',
    h1: 'Zones desservies',
    nav: 'Zones desservies',
    waText: 'Bonjour Valdir ! J’ai trouvé votre site et je voudrais savoir si vous intervenez dans ma ville.',
    mailSubject: 'Devis – intervention dans ma ville',
    paras: [
      '4V Manutencoes est basé à Jacareí, dans la vallée du Paraíba, et assure la maintenance d’équipements médicaux, de laboratoire et dentaires à São Paulo, dans tout le Grand São Paulo, dans la vallée du Paraíba et sur le littoral nord.',
      'L’entreprise est déjà intervenue à Jacareí, São José dos Campos, Caraguatatuba et Ubatuba, notamment pour la réparation d’autoclaves de la mairie d’Ubatuba. Elle a aussi l’expérience des laboratoires d’universités publiques comme l’USP, l’UNESP et l’Unifesp.',
      'Pour savoir si votre ville est desservie, écrivez sur WhatsApp en indiquant la ville, l’équipement et le problème.',
    ],
    citiesTitle: 'Villes où nous sommes déjà intervenus',
    cities: ['Jacareí', 'São José dos Campos', 'Caraguatatuba', 'Ubatuba'],
    regionsTitle: 'Régions',
    regions: ['Ville de São Paulo', 'Grand São Paulo (Grande São Paulo)', 'Vallée du Paraíba (Vale do Paraíba)', 'Littoral nord de l’État de São Paulo (Litoral Norte)'],
    outside: 'Vous êtes dans une autre ville ? Demandez sur WhatsApp.',
  },

  contato: {
    slug: 'contact',
    title: 'Contact : WhatsApp et e-mail | 4V Manutencoes',
    description: 'Écrivez sur WhatsApp au {phone} ou par e-mail à {email}. Formulaire de devis. Jacareí, État de São Paulo, Brésil.',
    h1: 'Contacter 4V Manutencoes',
    nav: 'Contact',
    waText: 'Bonjour Valdir ! J’ai trouvé le site de 4V Manutencoes et je voudrais un devis.',
    mailSubject: 'Devis – 4V Manutencoes',
    lead: 'WhatsApp est le moyen le plus rapide. Vous pouvez aussi envoyer un e-mail ou utiliser le formulaire ci-dessous.',
    tipsTitle: 'Pour accélérer le devis, indiquez :',
    tips: ['L’équipement, la marque et le modèle.', 'Ce qui se passe.', 'La ville où se trouve l’équipement.', 'Si possible, une photo de la plaque signalétique.'],
  },

  obrigado: {
    slug: 'merci',
    title: 'Message envoyé | 4V Manutencoes',
    description: 'Votre message a été envoyé à 4V Manutencoes.',
    h1: 'Message envoyé',
    nav: 'Message envoyé',
    waText: 'Bonjour Valdir ! Je viens d’envoyer un message depuis le site de 4V Manutencoes.',
    mailSubject: 'Devis – 4V Manutencoes',
    lead: 'Message envoyé. Valdir répondra par e-mail ou sur WhatsApp.',
    back: 'Retour à l’accueil',
  },

  notfound: {
    slug: '404',
    title: 'Page introuvable | 4V Manutencoes',
    description: 'Cette page n’existe pas.',
    h1: 'Page introuvable',
    nav: 'Page introuvable',
    waText: 'Bonjour Valdir ! J’ai trouvé le site de 4V Manutencoes et j’ai besoin d’une maintenance sur un équipement.',
    mailSubject: 'Devis – 4V Manutencoes',
    lead: 'Cette page n’existe pas ou a changé d’adresse.',
    back: 'Aller à l’accueil',
  },
};
